// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: spire/api/types/sovereignattestation.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
// A hardware-rooted PoR package produced by the Agent.
type SovereignAttestation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64-encoded TPM Quote (portable string). Validation: non-empty, base64, size <= 64kB
	TpmSignedAttestation string `protobuf:"bytes,1,opt,name=tpm_signed_attestation,json=tpmSignedAttestation,proto3" json:"tpm_signed_attestation,omitempty"`
	// The App Key public key (PEM or base64-encoded). Preferred format: PEM.
	// Validation: when present must parse; server-side validation enforced.
	AppKeyPublic string `protobuf:"bytes,2,opt,name=app_key_public,json=appKeyPublic,proto3" json:"app_key_public,omitempty"`
	// Optional base64-encoded DER or PEM certificate proving the App Key was issued/signed by the host AK.
	// **CLARIFICATION:** This field MUST be Base64-encoded when transmitted over a JSON/REST boundary (e.g., to Keylime).
	// Validation: when present must parse to X.509 cert; chain verification will be performed by Keylime.
	AppKeyCertificate []byte `protobuf:"bytes,3,opt,name=app_key_certificate,json=appKeyCertificate,proto3" json:"app_key_certificate,omitempty"`
	// The SPIRE Server nonce used for freshness verification.
	ChallengeNonce string `protobuf:"bytes,4,opt,name=challenge_nonce,json=challengeNonce,proto3" json:"challenge_nonce,omitempty"`
	// Optional workload code hash used as an additional selector/assertion.
	WorkloadCodeHash string `protobuf:"bytes,5,opt,name=workload_code_hash,json=workloadCodeHash,proto3" json:"workload_code_hash,omitempty"`
	// Unified-Identity - Phase 3: rust-keylime agent UUID for delegated certification correlation.
	KeylimeAgentUuid string `protobuf:"bytes,6,opt,name=keylime_agent_uuid,json=keylimeAgentUuid,proto3" json:"keylime_agent_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SovereignAttestation) Reset() {
	*x = SovereignAttestation{}
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SovereignAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SovereignAttestation) ProtoMessage() {}

func (x *SovereignAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SovereignAttestation.ProtoReflect.Descriptor instead.
func (*SovereignAttestation) Descriptor() ([]byte, []int) {
	return file_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{0}
}

func (x *SovereignAttestation) GetTpmSignedAttestation() string {
	if x != nil {
		return x.TpmSignedAttestation
	}
	return ""
}

func (x *SovereignAttestation) GetAppKeyPublic() string {
	if x != nil {
		return x.AppKeyPublic
	}
	return ""
}

func (x *SovereignAttestation) GetAppKeyCertificate() []byte {
	if x != nil {
		return x.AppKeyCertificate
	}
	return nil
}

func (x *SovereignAttestation) GetChallengeNonce() string {
	if x != nil {
		return x.ChallengeNonce
	}
	return ""
}

func (x *SovereignAttestation) GetWorkloadCodeHash() string {
	if x != nil {
		return x.WorkloadCodeHash
	}
	return ""
}

func (x *SovereignAttestation) GetKeylimeAgentUuid() string {
	if x != nil {
		return x.KeylimeAgentUuid
	}
	return ""
}

// Unified-Identity - Phase 1: SPIRE API & Policy Staging (Stubbed Keylime)
// AttestedClaims contains verified facts from Keylime about the host.
type AttestedClaims struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Geolocation    *Geolocation           `protobuf:"bytes,1,opt,name=geolocation,proto3" json:"geolocation,omitempty"`                             // Geolocation object with type, sensor_id, and optional value
	MnoEndorsement *MNOEndorsement        `protobuf:"bytes,2,opt,name=mno_endorsement,json=mnoEndorsement,proto3" json:"mno_endorsement,omitempty"` // Gen 4: Signed MNO endorsement
	// Gen 4: ZKP proof of proximity (Plonky2 proof)
	// In Commitment-Verification mode, this may be empty in the SVID cert.
	SovereigntyReceipt string `protobuf:"bytes,3,opt,name=sovereignty_receipt,json=sovereigntyReceipt,proto3" json:"sovereignty_receipt,omitempty"`
	// Cryptographic commitment to the full ZKP proof (SHA-256)
	SovereigntyReceiptHash string `protobuf:"bytes,4,opt,name=sovereignty_receipt_hash,json=sovereigntyReceiptHash,proto3" json:"sovereignty_receipt_hash,omitempty"`
	// URI reference to fetch the full proof out-of-band (e.g. from Depository)
	SovereigntyReceiptUri string `protobuf:"bytes,5,opt,name=sovereignty_receipt_uri,json=sovereigntyReceiptUri,proto3" json:"sovereignty_receipt_uri,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AttestedClaims) Reset() {
	*x = AttestedClaims{}
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedClaims) ProtoMessage() {}

func (x *AttestedClaims) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedClaims.ProtoReflect.Descriptor instead.
func (*AttestedClaims) Descriptor() ([]byte, []int) {
	return file_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{1}
}

func (x *AttestedClaims) GetGeolocation() *Geolocation {
	if x != nil {
		return x.Geolocation
	}
	return nil
}

func (x *AttestedClaims) GetMnoEndorsement() *MNOEndorsement {
	if x != nil {
		return x.MnoEndorsement
	}
	return nil
}

func (x *AttestedClaims) GetSovereigntyReceipt() string {
	if x != nil {
		return x.SovereigntyReceipt
	}
	return ""
}

func (x *AttestedClaims) GetSovereigntyReceiptHash() string {
	if x != nil {
		return x.SovereigntyReceiptHash
	}
	return ""
}

func (x *AttestedClaims) GetSovereigntyReceiptUri() string {
	if x != nil {
		return x.SovereigntyReceiptUri
	}
	return ""
}

// Gen 4: MNOEndorsement represents a signed endorsement from a carrier
type MNOEndorsement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Verified        bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	EndorsementJson string                 `protobuf:"bytes,2,opt,name=endorsement_json,json=endorsementJson,proto3" json:"endorsement_json,omitempty"` // JSON-encoded endorsement data
	Signature       string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                                    // EdDSA signature
	KeyId           string                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`                               // Signing key ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MNOEndorsement) Reset() {
	*x = MNOEndorsement{}
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MNOEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MNOEndorsement) ProtoMessage() {}

func (x *MNOEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MNOEndorsement.ProtoReflect.Descriptor instead.
func (*MNOEndorsement) Descriptor() ([]byte, []int) {
	return file_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{2}
}

func (x *MNOEndorsement) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *MNOEndorsement) GetEndorsementJson() string {
	if x != nil {
		return x.EndorsementJson
	}
	return ""
}

func (x *MNOEndorsement) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MNOEndorsement) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// Geolocation represents privacy-preserving geolocation sensor metadata
type Geolocation struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Type         string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                     // "mobile" or "gnss"
	ClassId      string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`                // Sensor manufacturer/model identifier (e.g., "12d1:1433")
	IdentityHash string                 `protobuf:"bytes,3,opt,name=identity_hash,json=identityHash,proto3" json:"identity_hash,omitempty"` // Globally unique identity commitment: hash(Unique Anchor + Class ID)
	// Optional descriptive fields for logging (non-unique)
	Provider      string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"` // e.g., "Huawei", "u-blox"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geolocation) Reset() {
	*x = Geolocation{}
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geolocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geolocation) ProtoMessage() {}

func (x *Geolocation) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_sovereignattestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geolocation.ProtoReflect.Descriptor instead.
func (*Geolocation) Descriptor() ([]byte, []int) {
	return file_spire_api_types_sovereignattestation_proto_rawDescGZIP(), []int{3}
}

func (x *Geolocation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Geolocation) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *Geolocation) GetIdentityHash() string {
	if x != nil {
		return x.IdentityHash
	}
	return ""
}

func (x *Geolocation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

var File_spire_api_types_sovereignattestation_proto protoreflect.FileDescriptor

const file_spire_api_types_sovereignattestation_proto_rawDesc = "" +
	"\n" +
	"*spire/api/types/sovereignattestation.proto\x12\x0fspire.api.types\"\xa7\x02\n" +
	"\x14SovereignAttestation\x124\n" +
	"\x16tpm_signed_attestation\x18\x01 \x01(\tR\x14tpmSignedAttestation\x12$\n" +
	"\x0eapp_key_public\x18\x02 \x01(\tR\fappKeyPublic\x12.\n" +
	"\x13app_key_certificate\x18\x03 \x01(\fR\x11appKeyCertificate\x12'\n" +
	"\x0fchallenge_nonce\x18\x04 \x01(\tR\x0echallengeNonce\x12,\n" +
	"\x12workload_code_hash\x18\x05 \x01(\tR\x10workloadCodeHash\x12,\n" +
	"\x12keylime_agent_uuid\x18\x06 \x01(\tR\x10keylimeAgentUuid\"\xbd\x02\n" +
	"\x0eAttestedClaims\x12>\n" +
	"\vgeolocation\x18\x01 \x01(\v2\x1c.spire.api.types.GeolocationR\vgeolocation\x12H\n" +
	"\x0fmno_endorsement\x18\x02 \x01(\v2\x1f.spire.api.types.MNOEndorsementR\x0emnoEndorsement\x12/\n" +
	"\x13sovereignty_receipt\x18\x03 \x01(\tR\x12sovereigntyReceipt\x128\n" +
	"\x18sovereignty_receipt_hash\x18\x04 \x01(\tR\x16sovereigntyReceiptHash\x126\n" +
	"\x17sovereignty_receipt_uri\x18\x05 \x01(\tR\x15sovereigntyReceiptUri\"\x8c\x01\n" +
	"\x0eMNOEndorsement\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12)\n" +
	"\x10endorsement_json\x18\x02 \x01(\tR\x0fendorsementJson\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\"}\n" +
	"\vGeolocation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12#\n" +
	"\ridentity_hash\x18\x03 \x01(\tR\fidentityHash\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bproviderB7Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3"

var (
	file_spire_api_types_sovereignattestation_proto_rawDescOnce sync.Once
	file_spire_api_types_sovereignattestation_proto_rawDescData []byte
)

func file_spire_api_types_sovereignattestation_proto_rawDescGZIP() []byte {
	file_spire_api_types_sovereignattestation_proto_rawDescOnce.Do(func() {
		file_spire_api_types_sovereignattestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_api_types_sovereignattestation_proto_rawDesc), len(file_spire_api_types_sovereignattestation_proto_rawDesc)))
	})
	return file_spire_api_types_sovereignattestation_proto_rawDescData
}

var file_spire_api_types_sovereignattestation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spire_api_types_sovereignattestation_proto_goTypes = []any{
	(*SovereignAttestation)(nil), // 0: spire.api.types.SovereignAttestation
	(*AttestedClaims)(nil),       // 1: spire.api.types.AttestedClaims
	(*MNOEndorsement)(nil),       // 2: spire.api.types.MNOEndorsement
	(*Geolocation)(nil),          // 3: spire.api.types.Geolocation
}
var file_spire_api_types_sovereignattestation_proto_depIdxs = []int32{
	3, // 0: spire.api.types.AttestedClaims.geolocation:type_name -> spire.api.types.Geolocation
	2, // 1: spire.api.types.AttestedClaims.mno_endorsement:type_name -> spire.api.types.MNOEndorsement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spire_api_types_sovereignattestation_proto_init() }
func file_spire_api_types_sovereignattestation_proto_init() {
	if File_spire_api_types_sovereignattestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_api_types_sovereignattestation_proto_rawDesc), len(file_spire_api_types_sovereignattestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spire_api_types_sovereignattestation_proto_goTypes,
		DependencyIndexes: file_spire_api_types_sovereignattestation_proto_depIdxs,
		MessageInfos:      file_spire_api_types_sovereignattestation_proto_msgTypes,
	}.Build()
	File_spire_api_types_sovereignattestation_proto = out.File
	file_spire_api_types_sovereignattestation_proto_goTypes = nil
	file_spire_api_types_sovereignattestation_proto_depIdxs = nil
}
